Sprint 2
DariaZherebtsova/middle.messenger.praktikum.yandex pull request #7
Opened 2021-06-14 12:36 UTC by DariaZherebtsova

2021-06-15 12:28 UTC, avdoshenkov requested changes
Всё хорошо в целом, молодец! 👍 Несколько нюансов только учесть, и будет отлично вообще.

2021-06-15 12:28 UTC, avdoshenkov commented on src/components/block/block.ts
> +  // _componentDidUpdate(oldProps: TProps, newProps: TProps)
В версии кода, готовой к мёрджу в `main` лучше оставлять комментарии только те, что жизненно необходимы. Например, с пояснениями к функционалу или TODO.

Но `oldProps` и `newProps` лучше оставить и проверять, изменились ли пропсы, и только если изменились, тогда можно делать апдейт. Иначе апдейтов может быть слишком много. 

Также важный нюанс, метод, начинающийся с подчёркивания в имени, считается приватным, т.е. используется только внутри класса и не отдаётся наружу. И к нему должен обращаться уже публичный метод. Таким образом, нужно поменять реализации `_componentDidUpdate` и `componentDidUpdate ` местами.

2021-06-15 12:28 UTC, avdoshenkov commented on src/components/block/block.ts
> +  _element: HTMLElement = document.createElement('div');
Полям класса мы можем задать разные [типы видимости](https://www.typescriptlang.org/docs/handbook/2/classes.html#member-visibility). Рекомендую использовать эту возможность, тогда в ходе работы над кодом будет дополнительная проверка со стороны TypeScript.

В частности, поле, чьё имя начинается с подчёркивания, должно быть приватным (`private`). А, например, `props` — публичным (`public`).

2021-06-15 12:28 UTC, avdoshenkov commented on src/components/block/block.type.ts
> +export type TProps = Record<string, string>;
Отлично, что получилось поисследовать различные варианты! Думаю, что здесь можно для значений использовать тип `any`, поскольку и правда, слишком большой. разбег в типах пропсов. Там и строка может быть, и функция-обработчик тоже, поэтому зазорного ничего нет, чтобы тут использовать `Record<string, any>`

2021-06-15 12:28 UTC, avdoshenkov commented on src/components/input/input.hbs.ts
> +    <input name="{{name}}" type="{{type}}" value="{{value}}">
Для `input` можно добавить атрибут `id` (можно с тем же значением, что и `name`, главное удостовериться, что на странице такой `id` будет уникальным), тогда `label` можно будет ассоциировать с `input` через атрибут [`for`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#attr-for)

2021-06-15 12:28 UTC, avdoshenkov commented on src/modules/chatPreview/chatPreview.hbs.ts
>      <div class="font-size-smaller color-grey">{{time}}</div>
Для времени лучше использовать тег [`time`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time). Помимо того, что это с точки зрения семантики более корректный вариант, у тега также есть дополнительный атрибут `datetime`, в который можно записать дату в полном строковом виде или в стандарте ISO (в котором, скорее всего, и будет приходить дата с сервера. Например, `2021-06-112T19:00`)

2021-06-15 12:28 UTC, avdoshenkov commented on src/modules/msgFeed/msgFeed.hbs.ts
> +    <div class="msg-feed__date font-size-smaller">{{date}}</div>
Тут также стоит использовать тег `time`

2021-06-15 12:28 UTC, avdoshenkov commented on src/modules/msgFeed/msgFeed.hbs.ts
> +  <div class="msg-feed__msg-input">
С точки зрения семантики, этот блок — полноценная форма, у которой есть поле для ввода и кнопка для отправки этой формы. В этом случае кнопка отправки должна иметь тип `submit` (у кнопки прикрепления файла должен быть тогда тип `button`), а вывод в консоль данных (которые в дальнейшем могут быть переделаны на взаимодействие с сервером) поместить в обработчик события `submit` у формы.

Что это даёт помимо правильной семантики? Как минимум то, что у пользователя сохраняется привычный ему по другим интерфейсам паттерн — по нажатию на Enter произойдёт отправка сообщения. А произойдёт она потому, что для формы в браузерах по умолчанию реализована ассоциация нажатия на Enter и нажатия на кнопки отправки (та, у которой указан тип `submit`). Кроме того в браузерах может быть реализовано кеширование введённых в форму данных и тогда если мы случайно перейдём на другую страницу и вернёмся обратно, то данные не потеряются, а достанутся из кеша браузера.

2021-06-15 12:28 UTC, avdoshenkov commented on src/pages/profile/index.ts
> +      type: 'phone',
Для номера телефона используется тип [`tel`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/tel)

2021-06-15 12:28 UTC, avdoshenkov commented on src/pages/profile/index.ts
> +function onBlur(event) {
Тут можно задать тип для события

2021-06-15 12:28 UTC, avdoshenkov commented on src/pages/profile/index.ts
> +function submit(event) {
Тут тоже можно задать тип для события

2021-06-15 12:28 UTC, avdoshenkov commented on src/pages/profile/index.ts
> +    setTimeout(() => {
Пока HTTPRequest не срабатывает в полном виде такой вариант приемлем, но в целом лучше перенести дальнейшие действия в `then` и `catch` методы.  Либо же, даже в данном случае c неработающим полноценно запросом, лучше перенести действия в метод [`finally`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally)

2021-06-15 12:28 UTC, avdoshenkov commented on src/pages/profile/index.ts
> +  newPasswordRepeat: 'password',
Для нового пароля не происходит проверка на соответствие с тем, что введено в `newPassword`

2021-06-15 12:28 UTC, avdoshenkov commented on src/pages/registration/index.ts
> +  passwordRepeat: 'password',
Тут также не происходит проверки на соответствие паролей

2021-06-15 12:28 UTC, avdoshenkov commented on src/utils/HTTPrequest.ts
> +  if (typeof data !== 'object') {
Здесь проверку [пройдёт](https://learn.javascript.ru/types#type-typeof) и переменная `data`, имеющая значение `null`. Нужно её скорректировать

2021-06-15 12:28 UTC, avdoshenkov commented on src/utils/HTTPrequest.ts
> +        xhr.send(data);
Тут можно проверить данные, в каком виде они отправляются. Мы можем отправлять в `FormData` или преобразованный `JSON`. [Тут](https://learn.javascript.ru/xmlhttprequest#post-formdata) можно посмотреть подробнее

2021-06-16 11:20 UTC, DariaZherebtsova commented on src/components/block/block.ts
> +  // _componentDidUpdate(oldProps: TProps, newProps: TProps)
Как я понимаю, публичный метод нужен, что бы его можно было переопределить, а вызывается он из приватного по событию жизненного цикла.

2021-06-17 13:32 UTC, avdoshenkov requested changes
Пару мелочей заметил, в остальном всё отлично! Даже ещё заметил, что некоторые правки сама сделала (например, методы в `enum` перенесла) — молодец!

2021-06-17 13:32 UTC, avdoshenkov commented on src/pages/authorization/index.ts
> +    inputEl.value.parentElement.parentElement.querySelector('.error-message').textContent = '';
Так лучше не делать, потому что родитель может оказаться на другом уровне вложенности. Для этой задачи лучше в отдельную переменную через `closest` найти родителя, в который в том числе входит блок с ошибкой, и если он нашёлся, тогда внутри него найти уже этот элемент для ошибок (желательно тоже в отдельную переменную). И уже у него менять содержимое. То же самое и для блока в `if`.

Но круто, что используешь именно `textContent`, т.к. обычно все делают через `innerHTML`, а это [сказывается на производительности](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent#differences_from_innertext).

2021-06-17 13:32 UTC, avdoshenkov commented on src/pages/profile/index.ts
> +    inputEl.parentElement?.parentElement?.querySelector('.error-message').textContent = resultValidate.message;
Тут опять же лучше через `closest`

2021-06-17 13:32 UTC, avdoshenkov commented on src/pages/registration/index.ts
> +    inputEl.parentElement.parentElement.querySelector('.error-message').textContent = resultValidate.message;
Тут также лучше через `closest`

2021-06-17 13:32 UTC, avdoshenkov commented on src/pages/registration/index.ts
> +    if (inputs[5].inputElement.value !== inputs[6].inputElement.value) {
Смущает прямое указание на индекс поля, в теории номер может измениться (т.к., например, скроется или добавится ещё какое-то поле). Поэтому перед сравнением я бы в отдельные переменные нашёл из массива элементы c именами `password` и `repeatPassword`, и уже потом сравнивал значения.

В остальных формах с повторным вводом пароля также поправил на такой вид

2021-06-17 13:33 UTC, avdoshenkov commented on src/components/block/block.ts
> +  // _componentDidUpdate(oldProps: TProps, newProps: TProps)
Да, всё верно! Это я затупил

2021-06-17 16:35 UTC, DariaZherebtsova commented
Поменяла хранение инпутов, и теперь в функции onBlur нахожу нужный инпут и пользуюсь благами класса Input.

2021-06-17 20:12 UTC, avdoshenkov approved these changes
Отлично! 👍

2021-06-21 09:07 UTC, merged